<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>17 Exceptions | Inside the Java 2 Virtual Machine</title>
    <meta name="description" content="Inside the Java 2 Virtual Machine">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="main.css" type="text/css"/>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="twelve columns">

            <div class="row test">
                <h1>17 Exceptions</h1>
            </div>
            <div class="u-cf"></div>

            <div class="row">
                <div class="one-third column value">
                    <a class="button button-primary mod" href="16.html">Previous page</a>
                </div>
                <div class="one-third column value" style="text-align:center;">
                    <a class="button button-primary mod" href="index.html">Table of content</a>
                </div>
                <div class="one-third column value">
                    <a class="button button-primary mod u-pull-right" href="18.html">Next page</a>
                </div>
            </div>

            <div class="content index ">
                <div class="u-cf"></div>

                <div class="waka">
                    <hr> <h2> Exceptions </h2> <p> This chapter shows how exceptions are implemented in bytecodes. It describes the instruction for throwing an exception explicitly, explains exception tables, and shows how catch clauses work. </p> <p> Accompanying this chapter on the CD-ROM is an applet that interactively illustrates the material presented in the chapter. The applet, named <i> Play Ball! </i> , simulates the Java Virtual Machine executing a method that throws and catches exceptions. At the end of this chapter, you will find a description of this applet and the bytecodes it executes. </p> <p> <em> Throwing and Catching Exceptions </em> </p> <p> Exceptions allow you to smoothly handle unexpected conditions that occur as your programs run. To demonstrate the way the Java Virtual Machine handles exceptions, consider a class named <code> NitPickyMath </code> that provides methods that perform addition, subtraction, multiplication, division, and remainder on integers. <code> NitPickyMath </code> performs these mathematical operations the same as the normal operations offered by Java's <code> + </code> , <code> - </code> , <code> * </code> , <code> / </code> , and <code> % </code> operators, except the methods in <code> NitPickyMath </code> throw checked exceptions on overflow, underflow, and divide-by-zero conditions. The Java Virtual Machine will throw an <code> ArithmeticException </code> on an integer divide-by-zero, but will not throw any exceptions on overflow and underflow. The exceptions thrown by the methods of <code> NitPickyMath </code> are defined as follows : </p> <pre> <p> <code> begin </code> </p> <code> <p/> </code> <code> // On CD-ROM in file except/ex1/OverflowException.java <p> class OverflowException extends Exception { </p> <p> } </p> </code> <code> <p> </p> <p/> </code> <code> // On CD-ROM in file except/ex1/UnderflowException.java <p> class UnderflowException extends Exception { </p> <p> } </p> </code> <code> <p> </p> <p/> </code> <code> // On CD-ROM in file except/ex1/DivideByZeroException.java <p> class DivideByZeroException extends Exception { </p> <p> } </p> </code> <code> <p> </p> </code> <code> end </code> </pre> <p> <code> <code> <code> A simple method that catches and throws exceptions is the <code> remainder() </code> method of class <code> NitPickyMath </code> : </code> </code> </code> </p> <pre> <p> <code> begin </code> </p> <code> <p/> </code> <code> // On CD-ROM in file except/ex1/NitpickyMath.java <p> class NitpickyMath { </p> <p> </p> <p> static int add(int a, int b) </p> <p> throws OverflowException, UnderflowException { </p> <p> </p> <p> long longA = (long) a; </p> <p> long longB = (long) b; </p> <p> long result = a + b; </p> <p> if (result </p> </code> Integer.MAX_VALUE) { <p> throw new OverflowException(); </p> <p> } </p> <p> if (result &lt; Integer.MIN_VALUE) { </p> <p> throw new UnderflowException(); </p> <p> } </p> <p> return (int) result; </p> <p> } </p> <p> </p> <p> static int subtract(int minuend, int subtrahend) </p> <p> throws OverflowException, UnderflowException { </p> <p> </p> <p> long longMinuend = (long) minuend; </p> <p> long longSubtrahend = (long) subtrahend; </p> <p> long result = longMinuend - longSubtrahend; </p> <p> if (result  Integer.MAX_VALUE) { </p> <p> throw new OverflowException(); </p> <p> } </p> <p> if (result &lt; Integer.MIN_VALUE) { </p> <p> throw new UnderflowException(); </p> <p> } </p> <p> return (int) result; </p> <p> } </p> <p> </p> <p> static int multiply(int a, int b) </p> <p> throws OverflowException, UnderflowException { </p> <p> </p> <p> long longA = (long) a; </p> <p> long longB = (long) b; </p> <p> long result = a * b; </p> <p> if (result  Integer.MAX_VALUE) { </p> <p> throw new OverflowException(); </p> <p> } </p> <p> if (result &lt; Integer.MIN_VALUE) { </p> <p> throw new UnderflowException(); </p> <p> } </p> <p> return (int) result; </p> <p> } </p> <p> </p> <p> static int divide(int dividend, int divisor) </p> <p> throws OverflowException, DivideByZeroException { </p> <p> </p> <p> // Overflow can occur in division when dividing the </p> <p> // negative integer of the largest possible magnitude </p> <p> // (Integer.MIN_VALUE) by -1, because this would just flip </p> <p> // the sign, but there is no way to represent that number </p> <p> // in an int. </p> <p> if ((dividend == Integer.MIN_VALUE) &amp;&amp; (divisor == -1)) { </p> <p> throw new OverflowException(); </p> <p> } </p> <p> try { </p> <p> return dividend / divisor; </p> <p> } </p> <p> catch (ArithmeticException e) { </p> <p> throw new DivideByZeroException(); </p> <p> } </p> <p> } </p> <p> </p> <p> static int remainder(int dividend, int divisor) </p> <p> throws OverflowException, DivideByZeroException { </p> <p> </p> <p> // Overflow can occur in division when dividing the </p> <p> // negative integer of the largest possible magnitude </p> <p> // (Integer.MIN_VALUE) by -1, because this would just flip </p> <p> // the sign, but there is no way to represent that number </p> <p> // in an int. </p> <p> if ((dividend == Integer.MIN_VALUE) &amp;&amp; (divisor == -1)) { </p> <p> throw new OverflowException(); </p> <p> } </p> <p> try { </p> <p> return dividend % divisor; </p> <p> } </p> <p> catch (ArithmeticException e) { </p> <p> throw new DivideByZeroException(); </p> <p> } </p> <p> } </p> <p> } </p> <code> <p> </p> </code> <code> end </code> </pre> <p> <code> <code> <code> <code> The <code> remainder() </code> method simply performs the remainder operation ( <code> % </code> ) upon the two <em> <code> ints </code> </em> passed as arguments. The remainder operation throws an <code> ArithmeticException </code> if the divisor of the remainder operation is a zero. This method catches this <code> ArithmeticException </code> and throws a <code> DivideByZeroException </code> . </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> The difference between these two exceptions is that <code> DivideByZeroException </code> is <em> checked </em> and <code> ArithmeticException </code> is <em> unchecked </em> . Because the <code> ArithmeticException </code> is unchecked, a method need not declare this exception in a <code> throws </code> clause even though it might throw it. Any exceptions that are subclasses of either <code> Error </code> or <code> RuntimeException </code> are unchecked. ( <code> ArithmeticException </code> is a subclass of <code> RuntimeException </code> .) By catching <code> ArithmeticException </code> and then throwing <code> DivideByZeroException </code> , the <code> remainder() </code> method forces its clients to deal with the possibility of a divide-by-zero exception, either by catching it or declaring <code> DivideByZeroException </code> in their own <code> throws </code> clauses. </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> javac </code> generates the following bytecode sequence for the <code> remainder </code> method: </code> </code> </code> </code> </p> <pre> <p> <code> begin </code> </p> <code> <p/> </code> <code> // The main bytecode sequence for remainder(): <p> </p> <p> 0 iload_0  // Push local variable 0 (arg passed as dividend) </p> <p> // Push the minimum integer value </p> <p> 1 ldc #1 &lt;Integer -2147483648 </p> </code> <p> // If the dividend isn't equal to the minimum integer, </p> <p> // jump to the remainder calculation </p> <p> 3 if_icmpne 19 </p> <p> </p> <p> 6 iload_1  // Push local variable 1 (arg passed as divisor) </p> <p> // Push -1 </p> <p> 7 iconst_m1 </p> <p> // If the divisor isn't equal to -1, jump </p> <p> // to the remainder calculation </p> <p> 8 if_icmpne 19 </p> <p> // This is an overflow case, so throw an exception </p> <p> // Create a new OverflowException, push reference to </p> <p> // it onto the stack </p> <p> 11 new #4 &lt;Class OverflowException </p> <p> 14 dup      // Make a copy of the reference </p> <p> // Pop one copy of the reference and invoke the &lt;init&gt; </p> <p> // method of new OverflowException object </p> <p> 15 invokespecial #10 &lt;Method OverflowException() </p> <p> // Pop the other reference to the OverflowException </p> <p> // and throw it </p> <p> 18 athrow </p> <p> </p> <p> // Calculate the remainder </p> <p> </p> <p> 19 iload_0  // Push local variable 0 (arg passed as dividend) </p> <p> 20 iload_1  // Push local variable 1 (arg passed as divisor) </p> <p> 21 irem     // Pop divisor; pop dividend; calculate, push remainder </p> <p> 22 ireturn  // Return int on top of stack (the remainder) </p> <p> </p> <p> </p> <p> // The bytecode sequence for the catch (ArithmeticException) clause: </p> <p> </p> <p> 23 pop      // Pop the reference to the ArithmeticException </p> <p> // because it isn't used by this catch clause. </p> <p> 24 new #2 &lt;Class DivideByZeroException </p> <p> // Create and push reference to new object of </p> <p> // class DivideByZeroException. </p> <p> 27 dup      // Duplicate the reference to the new object on the top </p> <p> // of the stack because it must be both initialized </p> <p> // and thrown. The initialization will consume </p> <p> // the copy of the reference created by the dup. </p> <p> 28 invokespecial #9 &lt;Method DivideByZeroException() </p> <p> // Call the no-arg &lt;init&gt; method for the </p> <p> // DivideByZeroException to initialize it. This </p> <p> // instruction will pop the top reference to the object. </p> <p> 31 athrow   // Pop the reference to a Throwable object, in this </p> <p> // case the DivideByZeroException, </p> <p> // and throw the exception. </p> <p> </p> <code> <p> </p> </code> <code> end </code> </pre> <p> <code> <code> <code> <code> <code> The bytecode sequence of the <code> remainder() </code> method has two separate parts . The first part is the normal path of execution for the method. This part goes from pc offset zero through 22. The second part is the catch clause, which goes from pc offset 23 through 31. </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <em> The Exception Table </em> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> The <em> <code> irem </code> </em> instruction in the main bytecode sequence may throw an <code> ArithmeticException </code> . If this occurs, the Java Virtual Machine knows to jump to the bytecode sequence that implements the catch clause by looking up and finding the exception in a table. Each method that catches exceptions is associated with an <i> exception table </i> that is delivered in the class file along with the bytecode sequence of the method. The exception table has one entry for each exception that is caught by each try block. Each entry has four pieces of information: </code> </code> </code> </code> </code> </p> <ul> <li> <code> <code> <code> <code> <code> the start point </code> </code> </code> </code> </code> </li> <li> <code> <code> <code> <code> <code> the end point </code> </code> </code> </code> </code> </li> <li> <code> <code> <code> <code> <code> the pc offset within the bytecode sequence to jump to </code> </code> </code> </code> </code> </li> <li> <code> <code> <code> <code> <code> a constant pool index of the exception class that is being caught. </code> </code> </code> </code> </code> </li> </ul> <p> <code> <code> <code> <code> <code> The exception table for the <code> remainder() </code> method of class <code> NitPickyMath </code> is shown below: </code> </code> </code> </code> </code> </p> <pre> <p> <code> begin </code> </p> <code> <p/> </code> <code> Exception table: <p> from   to  target type </p> <p> 19    23    23   &lt;Class java.lang.ArithmeticException </p> </code> <code> <p> </p> </code> <code> end </code> </pre> <p> <code> <code> <code> <code> <code> <code> The above exception table indicates that from pc offset 19 through 22, inclusive, <code> ArithmeticException </code> is caught. The try block's endpoint value, listed in the table under the label "to", is always one more than the last pc offset for which the exception is caught. In this case the endpoint value is listed as 23, but the last pc offset for which the exception is caught is 22. This range, 19 to 22 inclusive, corresponds to the bytecode sequence that implements the code inside the try block of <code> remainder() </code> . The target listed in the table is the pc offset to jump to if an <code> ArithmeticException </code> is thrown between the pc offsets 19 and 22, inclusive. </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> If an exception is thrown during the execution of a method, the Java Virtual Machine searches through the exception table for a matching entry. An exception table entry matches if the current program counter is within the range specified by the entry, and if the exception class thrown is the exception class specified by the entry (or is a subclass of the specified exception class). The Java Virtual Machine searches through the exception table in the order in which the entries appear in the table. When the first match is found, the virtual machine sets the program counter to the new pc offset location and continues execution there. &nbsp;If no match is found, the virtual machine pops the current stack frame and rethrows the same exception. When the Java Virtual Machine &nbsp;pops the current stack frame, it effectively aborts execution of the current method and returns to the method that called this method. But instead of continuing execution normally in the previous method, it throws the same exception in that method, which causes the it to go through the same process of searching through the exception table of that method. </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> A Java programmer can throw an exception with a throw statement such as the one in the catch ( <code> ArithmeticException </code> ) clause of <code> remainder() </code> , where a <code> DivideByZeroException </code> is created and thrown. The bytecode that does the throwing is shown in Table 17-1: </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> Table 17-1. <strong> Throwing Exceptions </strong> </code> </code> </code> </code> </code> </code> </p> <table width="500"> <tbody> <tr> <td valign="top"> <strong> Opcode </strong> </td> <td valign="top"> <strong> Operand(s) </strong> </td> <td valign="top"> <strong> Description </strong> </td> </tr> <tr> <td valign="top"> <code> athrow </code> </td> <td valign="top"> (none) </td> <td valign="top"> pops Throwable object reference, throws the exception </td> </tr> </tbody> </table> <p> <code> <code> <code> <code> <code> <code> The <em> <code> athrow </code> </em> instruction pops the top word from the stack and expects it to be a reference to an object that is a subclass of <code> Throwable </code> (or <code> Throwable </code> itself). The exception thrown is of the type defined by the popped object reference. </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <i> <strong> Play Ball!: A Simulation </strong> </i> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> The <i> Play Ball! </i> Applet, shown in Figure 17-1, demonstrates a Java Virtual Machine executing a sequence of bytecodes. This applet is embedded in a web page on the CD-ROM in file <code> applets/PlayBall.html </code> . The bytecode sequence in the simulation was generated by <tt> javac </tt> for the <code> playBall </code> method of the class shown below: </code> </code> </code> </code> </code> </code> </p> <pre> <p> <code> begin </code> </p> <code> <p/> </code> <code> // On CD-ROM in file except/ex2/Ball.java <p> class Ball extends Exception { </p> <p> } </p> </code> <code> <p> </p> <p/> </code> <code> // On CD-ROM in file except/ex2/Pitcher.java <p> class Pitcher { </p> <p> </p> <p> private static Ball ball = new Ball(); </p> <p> </p> <p> static void playBall() { </p> <p> int i = 0; </p> <p> for (;;) { </p> <p> try { </p> <p> if (i % 4 == 3) { </p> <p> throw ball; </p> <p> } </p> <p> ++i; </p> <p> } </p> <p> catch (Ball b) { </p> <p> i = 0; </p> <p> } </p> <p> } </p> <p> } </p> <p> } </p> </code> <code> <p> </p> </code> <code> end </code> </pre> <p> <code> <code> <code> <code> <code> <code> <code> <code> The bytecodes generated by <tt> javac </tt> for the <code> playBall </code> method are shown below: </code> </code> </code> </code> </code> </code> </code> </code> </p> <pre> <p> <code> begin </code> </p> <code> <p/> </code> <code> // The main bytecode sequence for playBall(): <p> </p> <p> 0 iconst_0      // Push constant 0 </p> <p> 1 istore_0      // Pop into local var 0: int i = 0; </p> <p> // The try block starts here (see the </p> <p> // exception table, below). </p> <p> 2 iload_0       // Push local var 0 </p> <p> 3 iconst_4      // Push constant 4 </p> <p> 4 irem          // Calc remainder of top two operands </p> <p> 5 iconst_3      // Push constant 3 </p> <p> 6 if_icmpne 13  // Jump if remainder not equal to 3: </p> <p> // if (i % 4 == 3) { </p> <p> // Push the static field at constant pool </p> <p> // location #6, which is the Ball exception eager </p> <p> // to be thrown </p> <p> 9 getstatic #6 &lt;Field Ball ball </p> </code> <p> 12 athrow        // Heave it home: throw ball; </p> <p> 13 iinc 0 1      // Increment the int at local var 0 by 1: ++i; </p> <p> // The try block ends here (see the </p> <p> // exception table, below). </p> <p> 16 goto 2        // jump always back to 2: for (;;) {} </p> <p> </p> <p> // The bytecode sequence for the catch (Ball) clause: </p> <p> </p> <p> 19 pop           // Pop the exception reference because it is unused </p> <p> 20 iconst_0      // Push constant 0 </p> <p> 21 istore_0      // Pop into local var 0: i = 0; </p> <p> 22 goto 2        // Jump always back to 2: for (;;) {} </p> <p> </p> <p> Exception table: </p> <p> from   to  target type </p> <p> 2    16    19   &lt;Class Ball </p> <code> <p> </p> </code> <code> end </code> </pre> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> The <code> playball() </code> method loops forever. Every fourth pass through the loop, <code> playball() </code> throws a <code> Ball </code> and catches it, just because it's fun. Since the try block and the catch clause are both within the endless while loop, the fun never stops. The local variable <em> <code> i </code> </em> starts at 0 and increments each pass through the loop. When the <code> if </code> statement is <code> true </code> , which happens every time <em> <code> i </code> </em> is equal to 3, the <code> Ball </code> exception is thrown. </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> The Java Virtual Machine checks the exception table and discovers that there is indeed an applicable entry. The entry's valid range is from 2 to 15, inclusive, and the exception is thrown at pc offset 12. The exception caught by the entry is of class <code> Ball </code> , and the exception thrown is of class <code> Ball </code> . Given this perfect match, the virtual machine pushes the thrown exception object onto the stack, and continues execution at pc offset 19. The catch clause, which starts at offset 19, merely resets <em> <code> int </code> </em> <em> <code> i </code> </em> to 0, and the loop starts over. </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> To drive the <i> Play Ball! </i> simulation, use the Step, Reset, Run, and Stop buttons . Each time you press the Step button, the simulator will execute the instruction pointed to by the pc register. If you press the Run button, the simulation will continue with no further coaxing on your part until you press the Stop button. To start the simulation over, press the Reset button. For each step of the simulation, a panel at the bottom of the applet contains an explanation of what the next instruction will do. Happy clicking. </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> <img src="images/fig17-1.gif" alt= "figure 17-1"> </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> <em> On the CD-ROM </em> </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> The CD-ROM contains the source code examples from this chapter in the <code> except </code> directory. The <i> Play Ball! </i> applet is contained in a web page on the CD-ROM in file <code> applets/PlayBall.html </code> . The source code for this applet is found alongside its class files, in the <code> applets/JVMSimulators </code> and <code> applets/JVMSimulators/COM/artima/jvmsim </code> directories. </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> <em> The Resources Page </em> </code> </code> </code> </code> </code> </code> </code> </code> </code> </p> <p> <code> <code> <code> <code> <code> <code> <code> <code> <code> For more information about the material presented in this chapter, visit the resources page: <code> http://www.artima.com/insidejvm/except.html </code> . </code> </code> </code> </code> </code> </code> </code> </code> </code> </p>

                </div>

            </div>
            <br/>
            <div class="u-cf"></div>

            <div class="row">
                <div class="one-third column value">
                    <a class="button button-primary mod" href="16.html">Previous page</a>
                </div>
                <div class="one-third column value" style="text-align:center;">
                    <a class="button button-primary mod" href="index.html">Table of content</a>
                </div>
                <div class="one-third column value">
                    <a class="button button-primary mod u-pull-right" href="18.html">Next page</a>
                </div>
            </div>
            <hr/>

        </div>

    </div>

</div>

</body>
</html>


